name: Pull Request Checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce Conventional PR Title Format
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            test
            refactor
            style
            ci
            build
          requireScope: true
          scopePattern: ^(NO-JIRA|ISE-\d+)$
          subjectPattern: ^(?![A-Z]).+$
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
